### ISSUE TITLE
invalid multibyte char (US-ASCII) (SyntaxError) error on running "bundle exec rake spec"

### ISSUE THREAD

**Issue by vinaysolanki** [thebigdb/akiva#2]
The issue happens because of « symbol that ruby is not able to identify unless you specify the encoding.

Solution: Include "# encoding: utf-8" in all .rb files or use 'magic_encoding' gem

**Comment by chrismaximin** [comment]
My apologies, I guess you're running it under ruby 1.9.x, I was only working on it under ruby 2.1.0;
I'll add a travis check to help.

**Comment by vinaysolanki** [comment]
Cool, thanks Chris!! I think it's time for me to move to 2.1 as well.

**Comment by chrismaximin** [comment]
Thanks for raising the issue ;)

**Comment by vinaysolanki** [comment]
No problem! I love the idea and would like to contribute more :)
